name: sgcraft_censor_word
main: me.arrow.sgcraft_censor_word.Main
version: 1.3
author: Arr0w
api-version: 1.16
commands:
    censorword:
      usage: /<command>
permission:
    censorword.wordconfig.service:
      default: op
      description: Can manage the censor word plugin